name: 小活动抽奖

on:
  workflow_dispatch:
  schedule:
    - cron: "20 16-20 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run App
      run: |
        python lottery.py
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_LOTTERYLIST_URL: ${{ secrets.JD_LOTTERYLIST_URL }}
        # TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        # TG_USER_ID: ${{ secrets.TG_USER_ID }}
